### ISSUE TITLE
Make quantity dimension documentation consistent

### ISSUE THREAD

**Issue by iliekturtles** [iliekturtles/uom#127]
Ensure comments use base units are listed in the same order as the base quantities are specified in the `system!` macro. Should units with a superscript of 1 be shown? Looks like most locations do show the superscript but a few don't. I'm leaning towards showing but welcome input.

Please reply here if you're interested in reviewing and making necessary changes. If no one else has noted their interested I plan on doing the review in the next couple days.

No superscripts shown. Should they be?
```rust
//! Electric charge (base unit coulomb, A · s).
```

Superscrit shown. Should it be?
```rust
//! Electric current (base unit ampere, A<sup>1</sup>).
```

Units are out of order. Should be m^1 * kg^1 * s^-2.
```rust
//! Force (base unit newton, kg<sup>1</sup> · m<sup>1</sup> · s<sup>-2</sup>).
```

**Comment by dunmatt** [comment]
Why is the important order for the documentation the one in the macro invocation?  That seems like a leaky abstraction.  What you really care about when writing documentation is what will be the easiest for the readers to understand.  In that light, I would suggest `Force` is not wrong.

The most familiar aspect of force to basically everyone is "F=ma", so it's naturally presented with an amount of mass times an amount of acceleration, kg * (m/s^2), and indeed this is how it is spelled out in Wikipedia.  m/s^2 * kg is worse because it is less familiar, but it's still much better than m * kg/s^2.

I guess what I'm saying is if I had my druthers the documentation would be optimized for the readers, even at the expense of the writers.  As far as the 1 superscripts, I'd say remove them because they're not typically used (even https://www.nist.gov/pml/nist-guide-si-appendix-b9-factors-units-listed-kind-quantity-or-field-science doesn't use them).

**Comment by Aehmlo** [comment]
@dunmatt This isn't so much a "leaky abstraction" as a strict interpretation of the specification. The [SI brochure](https://www.bipm.org/en/publications/si-brochure/section1-3.html) describes the 7 base dimensions exactly as they are arranged in this crate. As such, the *dimensions* in this crate arguably *must* be in the order they're written in.

The *units* in the crate and the ordering thereof is somewhat less black-and-white. From what I've read of the spec, there's not a clear statement of the expected order of units in terms of other units, but a strict interpretation would argue for (and convention seems to be) writing units in the same order as dimensions. I definitely see where you're coming from for stuff such as forces, but I also think that there's great value in consistency.

(If you're already aware of all of this and I'm just butting in where I shouldn't be, I apologize, but I figured I'd explain why it's the way it is.)

@iliekturtles I'd be happy to help out with this if needed/desired. I'm leaning rather heavily toward no superscripts for powers of 1 and appropriate Unicode codepoints instead of HTML tags.

**Comment by dunmatt** [comment]
I'm not sure what it means to have a "strict interpretation" when " there's not a clear statement of the expected order of units", how can you strictly interpret vague things?  But even setting that aside, why is SI fundamentalism a good thing?

I completely agree that there is great value in consistency.  Where we disagree is who should be the beneficiary of that great value.  You seem to believe it should be the people who both interact with the source of this crate and who happen to be deeply familiar with the SI brochure.  I follow Google in the opinion that one should "[Focus on the user and all else will follow.](https://www.google.com/about/philosophy.html)".  Since in this case it is a question of the design of documentation I take the user to be people who have an imperfect understanding of the crate but who want to use it for some purpose.

On your idea of appropriate Unicode codepoints, could those run into browser/font/OS compatibility problems?

**Comment by iliekturtles** [comment]
Thanks for the feedback! After a bit of my own [reading](https://jcgm.bipm.org/vim/en/1.7.html) I believe we should do the following. See the example below.

 * For the module documentation list the quantity followed by the base unit fully spelled out and then the base units of the base quantities. List base quantity units in their commonly used order or if there is no commonly used order then in the order as defined in the system. No 1 or 0 superscripts. Any additional documentation for the module should follow in the next paragraph.
 * The quantity documentation should have the same first line as the module. Any additional documentation should be in the next paragraph.
 * The dimension documentation should be reworded to "Dimension of [Q], L<sup>α</sup>M<sup>β</sup>T<sup>γ</sup>I<sup>δ</sup>Θ<sup>ε</sup>N<sup>ζ</sup>J<sup>η</sup> (base unit [u], [base units of base quantities])." No 1 or 0 superscripts and the parenthetical portion is copied from the module/quantity documentation.
 * Using Unicode superscripts would be nice but I want to test that they work everywhere first. I *think* I went with HTML superscripts because there were issues with superscripts past 3 in some locations (4-9 are in a different Unicode block). Use the following to make sure all characters appear: `-⁻2²3³4⁴5⁵6⁶7⁷8⁸9⁹`
   - [x] Windows 10. Everywhere I checked worked.
   - [ ] Windows 7. End of support is less than a year away.
   - [ ] Mac
   - [ ] Linux

```rust
//! Force (base unit newton, kg · m · s<sup>-2</sup>).

quantity! {
    /// Force (base unit newton, kg · m · s<sup>-2</sup>).
    quantity: Force; "force";
    /// Dimension of force, LMT<sup>-2</sup> (base unit newton, kg · m · s<sup>-2</sup>).
    dimension: ISQ<...>
}
```

**Comment by Aehmlo** [comment]
The Unicode characters look fine in the three major browsers on Mac.

**Comment by iliekturtles** [comment]
@Aehmlo What about in a `println!` to the console?

**Comment by Aehmlo** [comment]
Like you said, the documentation stuff only matters in a browser, but the superscripts also look fine in both iTerm 2 and the built-in Terminal app, both with default display settings.

**Comment by iliekturtles** [comment]
I was able to check on a Win Server 2008 R2 which I think shares similar components as Win 7. Everything looks good in the browser but only `²` works in the command prompt. Let's switch to the Unicode characters for any documentation but stay away from them in string literals at this time.

@Aehmlo If you're working on this let me know, otherwise I'll pick it up this week.

**Comment by Aehmlo** [comment]
Sure, I can do this. Should be able to get it done in the next couple of days.

**Comment by Aehmlo** [comment]
Style question: do we prefer "dimension of acceleration" (akin to "dimension of force" from above) or "acceleration dimension?" Some things, like "dimension of angle," sound somewhat strange, but I suppose they are technically correct.

**Comment by iliekturtles** [comment]
Thanks!

"dimension of X" (see notes at https://jcgm.bipm.org/vim/en/1.7.html)
