### ISSUE TITLE
Feature requrest: Need asin, acos, atan{,2} support on length

### ISSUE THREAD

**Issue by jerry73204** [iliekturtles/uom#168]
I had some work on Cartesian to spherical coordinate conversion with `uom`.
However, it lacks support on inverse trigonometric functions, and thus I have to use `get()` as workaround. Is it planned to add `asin`, `acos`, `atan` and `atan2` functions?

**Comment by iliekturtles** [comment]
Looks like these functions got missed when I created initial issues! They should be pretty easy to add. An `impl` block needs to be added to `Ratio` similar to the one for `Angle`:

https://github.com/iliekturtles/uom/blob/798149889b3720b1cb5546eeacab94aaecd8dc99/src/si/angle.rs#L29-L40

The inverse trigonometric functions can be added to return an `Angle`. I'd also like to have some discussion about whether the existing trigonometric functions on `Angle` should be changed to return `Ratio` instead of the underlying storage type.

Let me know if you're interested in submitting a PR, otherwise I'll try to get something going this week.
