### ISSUE TITLE
Add support for integral types as the underlying storage type

### ISSUE THREAD

**Issue by iliekturtles** [iliekturtles/uom#29]
Add support for integral types (i8, u8, i16, u16, i32, u32, i64, u64, usize? isize?, i128, u128) as the underlying storage type so that users can create new systems which do not use a floating point type. Use features to control code generation. Not all methods may be applicable. Types shouldn't be implemented for the ISQ.

**Comment by iliekturtles** [comment]
Use traits from the [`num`](https://crates.io/crates/num) crate instead of explicitly implementing each type?

**Comment by radix** [comment]
I use a bunch of integers in my code now, and that's why I'm not using uom yet. I think the `num` crate is a great idea for this. Note that it also has traits for floating point numbers which would allow you to generalize your float storage backends too (maybe?).

**Comment by iliekturtles** [comment]
I'm planning to start work on this issue after #3. I have a proof of concept for that issue but I've been pretty busy with summer activities. I haven't taken a look yet, but my understanding of `num` is that I should be able to completely generalize the underlying storage type. The only thing I'm not quite sure how to handle yet is the literal conversion factors.

If your code is open source I'd love to take a look when I start in on this issue to make sure a `num` trait-based solution works.

**Comment by radix** [comment]
Hi @iliekturtles ! Yep, my code is open source, but it's pretty embarrassing with respect to its handling units now. The project is [P&T](https://github.com/radix/pandt) and I have, for example, types like a [Distance type](https://github.com/radix/pandt/blob/master/pandt/src/types.rs#L243) which just stores centimeters as a u32 and Point3 as a three-tuple of i16s (meters). Of course the fact that these representations and methods are embarrassing is why I want to switch to uom :)

You can consider it basically like a representation of a board-game or something like minecraft, with positions in discrete blocks. That's why I'm using integers. Most data can deal with integral meters, and occassionally I drop down to centimeters for certain things (especially dealing with lines drawn at an angle, but I still don't need anything more precise than a cm).

**Comment by radix** [comment]
I just want to say that I've been following your development with interest and I'm very grateful that you're doing it :)

**Comment by iliekturtles** [comment]
Thanks for the positive feedback! I'm getting really close now. I _just_ need to get all the tests passing. Once that is done I'm planning to put together a PR to replace `Distance`.
