### ISSUE TITLE
Add newton_per_square_millimeter in Pressure

### ISSUE THREAD

**Issue by Eagle941** [iliekturtles/uom#395]
As per title, would it be possible to add `newton_per_square_millimeter` as available unit under Pressure?

**Comment by iliekturtles** [comment]
Easily!

Add a definition for the unit in the `units { ...` section:
https://github.com/iliekturtles/uom/blob/34538a91bea2703d8a072f61f31ac79a545eb90a/src/si/pressure.rs#L36-L40

And a test at the bottom:
https://github.com/iliekturtles/uom/blob/34538a91bea2703d8a072f61f31ac79a545eb90a/src/si/pressure.rs#L131-L135

PRs welcome, otherwise I can get to this after reviewing a couple open PRs.

**Comment by Eagle941** [comment]
Thank you for your answer! I have just opened #397
