### ISSUE TITLE
Quantity aliasing

### ISSUE THREAD

**Issue by Aehmlo** [iliekturtles/uom#78]
There are applications where units that evaluate to the same thing have very different meanings (torque vs. work, pressure vs. stress, etc.). It seems less-than-ergonomic to me to require the user to use `si::pressure::megapascal` (or `use si::pressure as stress` or whatever) for a stress of 1 MPa, for instance. I would like to see some way to have units duplicated under another name using DRY principles, although I'm not sure what this would look like (possibly just some new syntax in the `system!` macro?).

**Comment by iliekturtles** [comment]
I've been thinking/experimenting with this for a long time under #3 because thermodynamic temperature and temperature interval both have the same dimensions. Will continue my efforts under this issue since the problem is spelled out explicitly.

Current thought is to add another `PhantomData` member to `Dimension` to distinguish between quantities with the same actual dimensions. I haven't fully explored the idea however.
